services:
  inkscreen:
    # build: .
    image: ghcr.io/tim4431/inkscreen:main
    container_name: inkscreen
    restart: unless-stopped
    volumes:
      # 配置文件挂载
      - ./config.yaml:/app/config.yaml:ro
      - ./secrets.yaml:/app/secrets.yaml:ro
      - ./output:/app/output
      - ./assets:/app/assets
    environment:
      - TZ=America/Los_Angeles
    tty: true
