homeassistant:
  url: "http://<your-home-assistant-ip>:8123"
  token: "<your-long-lived-access-token>"

inkscreen:
  host: <your-inkscreen-ip>  #
  enable: true               # refresh the Inkscreen display
  clear_at_start: true       # clear the display at program start