name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# allow GITHUB_TOKEN to write to the registry
permissions:
  contents: read          # checkout still works
  packages: write         # needed to push to ghcr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1 – authenticate to ghcr
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # whoever triggered the run
          password: ${{ secrets.GITHUB_TOKEN }}  # built‑in token with package‑write scope

      # 2 – produce convenient tags & labels
      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 3 – build *and* push in a single step
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}   # only push on real branch pushes
          tags: ${{ steps.meta.outputs.tags }}       # e.g. ghcr.io/owner/repo:sha‑short, :latest …
          labels: ${{ steps.meta.outputs.labels }}
